### ISSUE TITLE
Add users without groups

### ISSUE THREAD

**Issue by sidekick-eimantas** [awslabs/ssosync#101]
Users that do not belong to any groups should be synced in as well. Right now they're ignored.

**Comment by ChrisPates** [comment]
Apologies this feature was never implemented. Working on it now in a feature branch. It will also support multiple queries (implementing that feature for groups, in the same sprint).

**Comment by omer2500** [comment]
@ChrisPates Any eta on those features?

**Comment by ChrisPates** [comment]
I'm working on it in a branch currently. You'll have the ability to perform group/user matching (multiple queries), include group/user, ignore group/user and finally flatten nested groups into the top level group.

**Comment by Indransh** [comment]
@ChrisPates How can one track the progress for this feature? There are related PRs that were closed in favor of [feature-EnhancedMatch](https://github.com/awslabs/ssosync/tree/feature-EnhancedMatch), but the last commit on that branch is 2+ months old.

Is this feature still on the roadmap? If you have a list of open issues for your feature branch, maybe we could help by contributing?

**Comment by ChrisPates** [comment]
Apologies, I’ve had to prioritise other projects for a couple of months. Thank you for the offers of assistance they are much appreciated. I’m planning on getting back into this branch in about 10 days, once I have dealt with some of the items I was part way through, I’ll be in touch. 

At the moment I’ve been focused on some fairly heavy read storing so the modules make much logical sense.

Once that is done and all the test have been reworked to match, it should be much easier to contribute features.

Kind regards,

Chris


On 23 Apr 2023, at 18:38, sidekick-eimantas ***@***.***> wrote:

﻿


@ChrisPates How can one track the progress for this feature? There are related PRs that were closed in favor of feature-EnhancedMatch <https://github.com/awslabs/ssosync/tree/feature-EnhancedMatch> , but the last commit on that branch is 2+ months old.

Is this feature still on the roadmap? If you have a list of open issues for your feature branch, maybe we could help by contributing?

Second. We have a go dev in house that could help out if needed

**Comment by et304383** [comment]
This is a critically missing feature.  As I just discovered that you delete any groups that you did not sync from GW. That is terrible.  If I wanted to delete groups that do not line up with GW, I would do it myself.  Shame on you for such destructive default behaviour.
