### ISSUE TITLE
SSO syns failed: error creating user (it tried to create existing user and fails)

### ISSUE THREAD

**Issue by AlKapkone** [awslabs/ssosync#104]
Hi, I use the latest **1.0.0-rc.10** version of ssosync and it fails for the last 2 week and I don't undestand what is the root cause.
The sync process fails on the random user which is already exists. What should I do to fix this issue ?

```
{
    "level": "debug",
    "msg": "updating aws users updated in google",
    "time": "2022-11-03T11:45:39Z"
}
{
    "level": "info",
    "msg": "creating user",
    "time": "2022-11-03T11:45:39Z",
    "user": "john.doe@example.com"
}
{
    "level": "error",
    "msg": "error creating user",
    "time": "2022-11-03T11:45:39Z",
    "user": "john.doe@example.com"
}
status of http response was 409: errorString
null
```

**Comment by AlKapkone** [comment]
@ChrisPates @christiangda
Hi, sorry to bother you, but do you have any idea what is the root cause of this issue ?
Thanks in advance.

**Comment by christiangda** [comment]
hi @AlKapkone , sorry I can't help you with this issue.  I abandoned this project almost 1 year ago after the conflict with the version and PRs.

I dedicated my time to creating a new one from scratch if you want to try it here is the link:  https://github.com/slashdevops/idp-scim-sync

**Comment by AlKapkone** [comment]
Thanks, @christiangda for your reply.

**Comment by sylwit** [comment]
Hi @AlKapkone, 

I was having the same issue today and it's related to this issue https://github.com/awslabs/ssosync/issues/65

I found a workaround by building ssosync from this fork https://github.com/DNXLabs/ssosync then package the lambda with AWS SAM and finally update the lambda provided by the ssosync application to use the new version.

But I'll give a try to https://github.com/slashdevops/idp-scim-sync since it makes month that dev are providing PR and no one merge them.

**Comment by AlKapkone** [comment]
@sylwit Hi, Sylvain
Thank you for your reply. Actually, I used to deploy my current aws sssosync lambda using AWS Lambda Application SSOSync — version 1.0.0-rc.10 (Author: Sebastian Doell).
Actually what should I do in this my case to start using the https://github.com/DNXLabs/ssosync as a source for Lambda and don't recreate everything.

I downloaded the https://github.com/DNXLabs/ssosync source and update template.yaml file:
```
    HomePageUrl: https://github.com/DNXLabs/ssosync
    # Update the semantic version and run sam publish to publish a new version of your app
    SemanticVersion: v1.0.0-rc.10
    # best practice is to use git tags for each release and link to the version tag as your source code URL
    SourceCodeUrl: https://github.com/DNXLabs/ssosync/tree/v1.0.0-rc.10
```
After that I packaged and uploaded the updated function to the bucket, as result I have 3 files (including .zip archieve).
```
make package
```
And the last step - how to update my CloudFormation template ? Have you created a change set ? Or just updated the existing CF stack ?

**Comment by AlKapkone** [comment]
<img width="1379" alt="Screenshot 2022-11-04 at 13 39 26" src="https://user-images.githubusercontent.com/24461114/199964033-9a2fcdd6-78e5-4b63-82d7-fb2440f297fa.png">
Here you can see packaged and uploaded the function to the bucket.

**Comment by AlKapkone** [comment]
```
  SSOSyncFunction:
    Type: 'AWS::Lambda::Function'
    Metadata:
      SamResourceId: SSOSyncFunction
    Properties:
      Code:
        S3Bucket: awsserverlessrepo-changesets-1iiv3xa62ln3m
        S3Key: >-
          976322870513/arn:aws:serverlessrepo:us-east-2:004480582608:applications-SSOSync-versions-1.0.0-rc.9/19ba85eb-c509-4ad4-aa4d-66c683d81059
```
Now I'm going to update the **S3Bucket** and **S3Key** properties to new ones (created in the previous step using `make package` command).

**Comment by ChrisPates** [comment]
Apologies, I was out on leave.

@sylwit is correct, this is sadly not a new issue and relates to certain limitations in the SCIM api. Which has made it difficult to address. Recently the IAM Identity Manager team released the a new [api](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/welcome.html) for IdentityStore. Which has given the ssosync project an opportunity to make some improvements. 

I have a pull request to review, that should address this and a number of other long standing issues. I aim to complete this by the end of next week.

**Comment by AlKapkone** [comment]
@ChrisPates Thank you. Will wait for these changes.

**Comment by ChrisPates** [comment]
Version 2.x of SSOSync should address, this.
