### ISSUE TITLE
Validate required parameters earlier

### ISSUE THREAD

**Issue by delenamalan** [awslabs/ssosync#122]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying to wait until all of the Google users have been fetched only to then find out that I missed some required parameters. As far as I understand, the `region` and `identity-store-id` parameters are now required. Please correct me if I'm wrong. :)

**Describe the solution you'd like**
It would be nice if the validation for the required parameters could be done before any syncing starts.

**Comment by ChrisPates** [comment]
Completely agree, I also want to add preflight checks of each api client to confirm access and permission are good before getting started.

**Comment by delenamalan** [comment]
Thank you, Chris! Very exciting that this project is getting some love. 😄

**Comment by ChrisPates** [comment]
This improvement has been merged in to master and will be released as part of v2.1.x
