### ISSUE TITLE
Add parameter for log retention

### ISSUE THREAD

**Issue by dm3ch** [awslabs/ssosync#124]
**Is your feature request related to a problem? Please describe.**
Now when you are installing SSOSync from AWS App marketplace you are unable to specify log retention period.

**Describe the solution you'd like**
I would like to have ability to provide existing log group to template or configure retention period of created log group

**Describe alternatives you've considered**

**Additional context**

**Comment by ChrisPates** [comment]
So this spin-it would make this configurable

  # Explicit log group that refers to the Lambda function
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Function}"
      # Explicit retention time
      RetentionInDays: 7

Would need to make it possible to still have Indefinite retention as an option, however un-frugle that may be.

**Comment by ChrisPates** [comment]
This improvement has been merged in to master and will be released as part of v2.1.x
