### ISSUE TITLE
SSOSync fails to get binary secrets

### ISSUE THREAD

**Issue by dancorne** [awslabs/ssosync#130]
**Describe the bug**
If any of the secrets for the Lambda are stored as binary rather than strings, SSOSync stops working with the following error:
```
{"level":"fatal","msg":"cannot read config: illegal base64 data at input byte 0","time":"2023-05-02T08:04:04Z"} 
```

**To Reproduce**
Update one of the secrets to use binary rather than string, eg with the command:
```
aws secretsmanager update-secret --secret-id SSOSyncGoogleCredentials --secret-binary $(cat credentials.json | base64)
```

**Expected behavior**
SSOSync fetches the secret and continues to run.

**Comment by ChrisPates** [comment]
This request has been merged with related one under a single feature request [Expand the Options for storing the sensitive parameters to include binaray secrets and SSM Parameter Store #180](https://github.com/awslabs/ssosync/issues/180]. Please review and add any specific requirements you feel it doesn't address.
