### ISSUE TITLE
Application in AWS Serverless Repository requires values for optional parameters 

### ISSUE THREAD

**Issue by spock-abadai** [awslabs/ssosync#132]
**Describe the bug**
When deploying the application from the AWS Serverless Application Repository, none of the fields can be left empty. The deployment fails with a warning similar to the attached.

![image](https://user-images.githubusercontent.com/118175475/236192038-36e6d0a9-d330-43ad-967b-028cd4dc4306.png)

This is problematic because:
1. It effectively forces users to use an explicit include list for groups.
2. It requires values for `GoogleGroupMatch`, `GoogleUserMatch`, `IgnoreGroups` and `IgnoreUsers`. While one can provide a wildcard filter for the former two (email:*) and a dummy value for the latter two, it is still a nuissance.

**To Reproduce**
1. Go to 'https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-2:004480582608:applications/SSOSync' 
2. Fill in all the arguments except `IncludeGroups`, and deploy

**Expected behavior**
It would be better if optional parameters can just be left empty and achieve behavior similar to omitting the parameter in the CLI.

**Comment by TomD3Wiz** [comment]
@ChrisPates Can you add that information to the docs, the Deploy via Serverless App is your recommended install.

**Comment by ChrisPates** [comment]
This has been addressed in v2.1. Thank you for your feedback.
