### ISSUE TITLE
Sync fails for user with apostrophe in email address

### ISSUE THREAD

**Issue by cgrice** [awslabs/ssosync#139]
**Describe the bug**
When syncing using the `groups` method, any users with an apostrophe in their email cause the sync to fail.

**To Reproduce**
1. Find a group with a user who has an email containing an apostrophe
1. Run a sync using `groups` mode, with a `--group-match` set to match that group
2. The sync fails with an "Error 400: Invalid Input: query, invalid" error

**Expected behavior**
The sync should work as expected, including the user with the apostrophe.

**Additional context**
I believe the issue is caused by these lines - https://github.com/awslabs/ssosync/blob/065189469236d528c98b95c170f6f4130ae013db/internal/sync.go#L565-L566 - there's a note to move to `GetUser(m.Email)` which I think would solve the issue.

I've managed to work around this by adding an email alias without an apostrophe, and ignoring the user in question with `--ignore-users`

**Comment by ChrisPates** [comment]
This should have been addressed v2.2.0, where we don't do per user queries, instead we have all users in a memory and pull the details from there.
