### ISSUE TITLE
Custom attributes not coming after user syncing

### ISSUE THREAD

**Issue by jogindercc** [awslabs/ssosync#143]
**Is your feature request related to a problem? Please describe.**
Not able to use ABAC(Attribute Based Access Control) for authorization custom permissions using conditions in policies.

**Describe the solution you'd like**
Currently, the users getting synced with ssosync tool, we're not getting  all of the Users' attributes. (Like: Department, Cost Center) etc.  We're just getting the primary attributes like Username,Email, First Name, Last Name only. However, on Google account we have created all the user attributes.
If we get this atrributes synced as well along with Users, We can leverage these attributes to have more fine grain control over access policies.

**Additional context**
Below is the screenshot of User's attributes not coming on the AWS, after sso-sync.

![image](https://github.com/awslabs/ssosync/assets/61409044/c99aec09-0762-4710-a702-cd6ff51be960)

**Comment by ChrisPates** [comment]
Apologies for the delay. So at the moment ssosync only populates a minimal set of attributes.
I'll define a feature request, to expand this to include as many as possible.

**Comment by ChrisPates** [comment]
Closing this issues, as currently this is expected behavior. Please review the feature request issue and add anything you would specifically like to see included.
