### ISSUE TITLE
Functions use deprecated go1.x Lambda Runtime

### ISSUE THREAD

**Issue by troyready** [awslabs/ssosync#145]
The [ssosync function is deployed using the go1.x runtime](https://github.com/awslabs/ssosync/blob/v2.0.3/template.yaml#L132), which has been [deprecated](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/). In practical terms, this will mean new new deployments will be possible after 2023 and existing deployments will not be able to be updated after 2024-01-31.

Should be simple enough to [swap the SAM build fields](https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html#golang-package-create-function) (unfortunate that there doesn't seem to be a way to pass the `lambda.norpc` golang build tag to slim down the package size but I wouldn't say that's a critical requirement).

Also probably worth updating the function architecture to graviton during this update get the price:performance boost.

**Comment by ChrisPates** [comment]
This improvement has been merged in to master and will be released as part of v2.1.x

**Comment by cswilliams** [comment]
@ChrisPates Just was curious when you were planning on releasing v2.1.x? The deprecation date is starting to get closer.  Thanks!

**Comment by ChrisPates** [comment]
I hope to have it released by this time next week. I’m currently updating all the CiCD pipelines to adequately test the new functionality.

Kind regards,

Chris

On 5 Dec 2023, at 18:53, Chris Williams ***@***.***> wrote:

﻿


@ChrisPates Just was curious when you were planning on releasing v2.1.x? The deprecation date is starting to get closer. Thanks!
