### ISSUE TITLE
support multiple group prefixes in groupMatch parameter

### ISSUE THREAD

**Issue by andrey-yakubovskiy** [awslabs/ssosync#156]
It should be possible to specify multiple group prefixes, e.g. `name:abc-* name:xyz-*` to cherry-pick groups for synchronisation. It looks like Google groups API doesn't support this but it can be emulated by making API call per group prefix and then concatenating the results in one group set.

**Comment by ChrisPates** [comment]
I have this behaviour working in a prototype for v3.x, I hope to get it released early in the new year.

Kind regards,

Chris 

On 29 Nov 2023, at 11:10, andrey-yakubovskiy ***@***.***> wrote:

﻿


It should be possible to specify multiple group prefixes, e.g. name:abc-* name:xyz-* to cherry-pick groups for synchronisation. It looks like Google groups API doesn't support this but it can be emulated by making API call per group prefix and then concatenating the results in one group set.

**Comment by julgachancipa** [comment]
Hello, I would like to know if there is any update on this.

**Comment by ChrisPates** [comment]
I'm going to pull this feature forward into v2.2, and is the next deliverable I'm working on. I had to park it for a while due to bugfixes to address changes in an up stream dependancy.
