### ISSUE TITLE
Question: Super Admin role required for Google Workspace admin user

### ISSUE THREAD

**Issue by jhecking** [awslabs/ssosync#161]
According to the docs (https://github.com/awslabs/ssosync#google) a Google Workspace "admin user" is required to sync the directory:

> You will have to specify the email address of an admin via --google-admin to assume this users role in the Directory.

Is it required that this admin user has the Super Admin role? Or can we use a different admin role with fewer privileges? We tried using a user with a custom admin role with just the "Users > Read" and "Groups > Read" privileges for the Admin API, but the sync failed with a 403 error.

**Comment by ChrisPates** [comment]
Currently it’s super admin, which is clearly less than ideal. There is a feature coming to use a service role. I’ll update this issue with the PR when I get back to my desk.


Chris

On 4 Jan 2024, at 10:10, Jan Hecking ***@***.***> wrote:

﻿


According to the docs (https://github.com/awslabs/ssosync#google <https://github.com/awslabs/ssosync#google> ) a Google Workspace "admin user" is required to sync the directory:

You will have to specify the email address of an admin via --google-admin to assume this users role in the Directory.

Is it required that this admin user has the Super Admin role? Or can we use a different admin role with fewer privileges? We tried using a user with a custom admin role with just the "Users > Read" and "Groups > Read" privileges for the Admin API, but the sync failed with a 403 error.

**Comment by jhecking** [comment]
Great! Thank you for the quick response.

**Comment by jhecking** [comment]
>  I’ll update this issue with the PR when I get back to my desk.

Hi @ChrisPates, any update on this? 🙏

**Comment by ChrisPates** [comment]
This issue #150, I'll be looking to include this in a future release.

**Comment by ricky26j** [comment]
I see this issue was marked as completed. Do we not need a super admin role anymore?
