### ISSUE TITLE
Group owners should be also a group members

### ISSUE THREAD

**Issue by Leny1996** [awslabs/ssosync#189]
**Describe the bug**
After update to latest version (2.2.2) I noticed that a lot of accounts has been removed, then noticed that all of those people were owners of a groups (also my account was removed, because I'm the owner of main group - it's good to have a backup account in IAM in that case).

I can see the notice on README:
> group owners and external users are ignored.

Question is, why group owners are not treated as group members? This is the default behavior of Google accounts and also it was working that way previously on SSOSync.

**Comment by ChrisPates** [comment]
Thanks for the feedback, will adjust handling so **Group Owners** are treated as **Group Members**, this will be released as v2.2.3. Hopefully by the end of the day.
