### ISSUE TITLE
segmentation violation

### ISSUE THREAD

**Issue by ScOut3R** [awslabs/ssosync#19]
Hey,

just installed the tool via go and getting the following error on a Linux machine:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa80b25]

goroutine 1 [running]:
github.com/awslabs/ssosync/internal/google.NewClient(0x100be40, 0xc0003a26c0, 0x0, 0x0, 0xc0003f8000, 0x1a2, 0x3a2, 0x0, 0x0, 0x15876e0, ...)
	/home/runner/work/ssosync/ssosync/internal/google/client.go:44 +0xd5
github.com/awslabs/ssosync/internal.DoSync(0x100be40, 0xc0003a26c0, 0xc0003c0780, 0xc0003a26c0, 0xc00039e9c0)
	/home/runner/work/ssosync/ssosync/internal/sync.go:251 +0x1e1
github.com/awslabs/ssosync/cmd.glob..func1(0x157b340, 0xc0003a2600, 0x0, 0x4, 0x0, 0x0)
	/home/runner/work/ssosync/ssosync/cmd/root.go:54 +0x89
github.com/spf13/cobra.(*Command).execute(0x157b340, 0xc00001e0b0, 0x4, 0x4, 0x157b340, 0xc00001e0b0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x157b340, 0x405cff, 0xc000076058, 0x0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/awslabs/ssosync/cmd.Execute()
	/home/runner/work/ssosync/ssosync/cmd/root.go:71 +0x3e
main.main()
	/home/runner/work/ssosync/ssosync/main.go:29 +0x20
```

```
go version go1.15.2 linux/amd64
```

Please let me know what other information you require from me.

**Comment by BaudouinH** [comment]
Hello, I also encountered this issue recently.

I solved this by making sure the credentials.json file was properly formatted, and it fixed the issue.

**Comment by ScOut3R** [comment]
> Hello, I also encountered this issue recently.
> 
> I solved this by making sure the credentials.json file was properly formatted, and it fixed the issue.

@BaudouinH, thank you for your reply. Could you please elaborate on what is properly formatted? I got the credentials.json file straight from the Google Console and it works well with other tools, like the Google Admin SDK.

**Comment by iserko** [comment]
@ScOut3R try pushing your credentials file through a tool like [jq](https://stedolan.github.io/jq/), to verify whether it's valid JSON ... I got the same error when I mistakenly removed all double quotes

**Comment by ScOut3R** [comment]
> @ScOut3R try pushing your credentials file through a tool like [jq](https://stedolan.github.io/jq/), to verify whether it's valid JSON ... I got the same error when I mistakenly removed all double quotes

Thanks for the tip @iserko , according to jq the file is valid.

**Comment by ScOut3R** [comment]
:facepalm: I was using the wrong credentials file. Switching to a service account the issue is gone. Thank you all for the assistance.
