### ISSUE TITLE
Lambda Function Failing with 401 Error After Updating SCIM Access Token

### ISSUE THREAD

**Issue by marvingoetz** [awslabs/ssosync#198]
After our IAM Identity Center SCIM Access Token expired, we created a new one and updated it within the CloudFormation template. The stack was successfully updated with the new SCIM Access Token parameter value. However, since the update, the Lambda function has been failing with the following error messages:

```
{
  "level": "error",
  "msg": "error getting active status for user 736...",
  "time": "2024-06-06T07:36:02Z"
}
{
  "level": "fatal",
  "msg": "Notifying Lambda and mark this execution as Failure: status of http response was 401",
  "time": "2024-06-06T07:36:02Z"
}
```

Is there any additional step required beyond replacing the Access Token to resolve this issue? For example on google site? We would appreciate any guidance on troubleshooting or potential fixes to ensure the Lambda function operates correctly with the new SCIM Access Token.

**Comment by ChrisPates** [comment]
There are two scenarios I have seen here.
