### ISSUE TITLE
AWS 429 on initial sync from repo with 200 accounts

### ISSUE THREAD

**Issue by cep21** [awslabs/ssosync#2]
I have 200 users.  The initial run of ssosync will not finish because eventually I get `status of http response was 429`.  This happens during the group syncing.

**Comment by grugnog** [comment]
I get this also.

**Comment by cep21** [comment]
Is there documentation from aws on request limits for sso api?

**Comment by katallaxie** [comment]
@cep21 can you test https://github.com/awslabs/ssosync/releases/tag/v1.0.0-rc.1

**Comment by grugnog** [comment]
@katallaxie this resolved things on the user side for me - I still got one 400 error (although only after many groups) - not sure if that was a limit or just a random fail though.

**Comment by katallaxie** [comment]
I close this issue, because it refers to an old version. @grugnog regarding `400` errors this would yield a ticket to the service team.

**Comment by grugnog** [comment]
@katallaxie I forgot to update my comment, but the 400 thing turned out to be #7
