### ISSUE TITLE
Deploying to GCP Cloud Functions

### ISSUE THREAD

**Issue by cloud-rocket** [awslabs/ssosync#20]
**Is your feature request related to a problem? Please describe.**
Sometimes it makes more sense to deploy this synchronization to GCP Cloud Functions. Since there is no need to export credentials out of GCP and in terms of more correct architecture - the parent provider (GCP) will be responsible to delegate the security to the undergoing provider (AWS)

**Describe the solution you'd like**
Provide instructions on how to deploy `ssosync` to GCP Cloud Functions and periodically call it with scheduler

**Comment by ChrisPates** [comment]
The recommend deployment pattern is as a lambda, launched from the Serverless Application Repository (SAR). Whilst I can appreciate your desire to deploy in this pattern, it creates a challenge for use to provide recommendation regarding someone else execution environment.
