### ISSUE TITLE
Name Handling

### ISSUE THREAD

**Issue by CarlosCuevas** [awslabs/ssosync#200]
[Names don't always fit into the first and last convention](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/).

For example, some people prefer to go by a mononym. The way to accommodate this, in many systems, is passing a zero width space as the last name (or some other character). At present, if a name with a zero width space is pulled from Google, it will cause an API failure when trying to create the user in AWS. It would be helpful to have the option of passing in a non-alphabetic character in one of the name fields (or whatever option that allows us to accommodate folks whose names don't fit into the first and last paradigm).

**Comment by ChrisPates** [comment]
So you are looking for if either name field is zero length replacing that filed with " " before calling the SCIM API on the AWS side?

**Comment by CarlosCuevas** [comment]
i think that would work

**Comment by CarlosCuevas** [comment]
with the caveat that the name wouldn't be zero length when its first pulled from google (since it has the zero width space)

**Comment by CarlosCuevas** [comment]
the AWS API does not accept an empty name but it did seem to accept a name with a zero width space. the tool itself seems to strip it out before sending it.
