### ISSUE TITLE
Set Concurrency Limit to 1 in CloudFormation Stack

### ISSUE THREAD

**Issue by CarlosCuevas** [awslabs/ssosync#206]
**Is your feature request related to a problem? Please describe.**
It's possible to have several instances of the lambda function simultaneously. This could lead to race conditions. I can't imagine any scenario where someone would want multiple executions of the lambda function simultaneously. 

**Describe the solution you'd like**
Set ~Reserve~ Concurrency Limit to 1 for the Lambda function within the CloudFormation Stack/AWS Serverless App Repo.

**Comment by sdemjanenko** [comment]
Wouldn't that incur costs when the lambda isn't actually executing? Is the problem an issue of locking (where one lambda execution is still running while another execution tries to start)? That could be solved by a locking structure in dynamo DB or potentially with step functions.

**Comment by ChrisPates** [comment]
This would be best practice approach https://aws.amazon.com/about-aws/whats-new/2017/11/set-concurrency-limits-on-individual-aws-lambda-functions/ <https://aws.amazon.com/about-aws/whats-new/2017/11/set-concurrency-limits-on-individual-aws-lambda-functions/> 

I t would be modest effort to implement, however it is unlikely to be necessary, in all be very specific combination of circumstances.

Chris

On 27 Jun 2024, at 20:28, Stephen Demjanenko ***@***.***> wrote:

﻿


Wouldn't that incur costs when the lambda isn't actually executing? Is the problem an issue of locking (where one lambda execution is still running while another execution tries to start)? That could be solved by a locking structure in dynamo DB or potentially with step functions.

**Comment by CarlosCuevas** [comment]
> Wouldn't that incur costs when the lambda isn't actually executing? Is the problem an issue of locking (where one lambda execution is still running while another execution tries to start)?

Yes, sorry. I may have misunderstood what I read. The goal is to block execution while another is in progress.

> I t would be modest effort to implement, however it is unlikely to be necessary, in all be very specific combination of circumstances.

We have the lambda function running every x minutes. Every so often an execution will exceed the x number of minutes and there will be > 1 running simultaneously.

Alternatively, we were considering having executions be triggered by changes in Google Workspace (as opposed to being timer based), but that runs the risk of triggering multiple if one is already in progress. Not being able to configure or limit It felt like a footgun.

**Comment by CarlosCuevas** [comment]
per [https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html](https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html)

> Reserved concurrency – This represents the maximum number of concurrent instances allocated to your function. When a function has reserved concurrency, no other function can use that concurrency. Reserved concurrency is useful for ensuring that your most critical functions always have enough concurrency to handle incoming requests. **Configuring reserved concurrency for a function incurs no additional charges.**

**Comment by ChrisPates** [comment]
The naming of these properties can be some what confusing.

**Comment by philomory** [comment]
I will note, for posterity, that if you create a new account to be the Delegated Administrator for your IAM Identity Center instance, and you install this lambda in that new account (or any other freshly created account), then even though the "default" quota for "Concurrent executions" is 1,000, the new account will have a "Concurrent executions" quota of 10. In theory this is supposed to automatically increase up to the "real" default of 1000 over time as you use Lambda, but another quirk of the "Concurrent executions" quota is that you can never have fewer than 10 "unreserved" executions, so, with the "Concurrent executions" limit at 10, deploying this app will fail with the error "Specified ConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of 10".

**Comment by maulerjan** [comment]
@philomory running into exactly the same issue. Any workaround?

**Comment by philomory** [comment]
> @philomory running into exactly the same issue. Any workaround?

Either request a quota increase, wait for it to be granted, and then deploy; or edit the YAML manifest file and set the concurrency to 0; or both (as in, request a quota increase, deploy with a manually edited YAML while waiting for it to be approved, and then edit the YAML back and deploy again)

**Comment by maulerjan** [comment]
Thanks! Deploying serverless app from template for the first time, didn't know the yaml could be edited
