### ISSUE TITLE
SCIMEndpointAccessToken too long

### ISSUE THREAD

**Issue by xelfer** [awslabs/ssosync#211]
![image](https://github.com/user-attachments/assets/e1b77d2b-129a-45cb-9c84-20eed5f07f1a)

My SCIMEndpointAccessToken freshly generated by AWS is 603 characters.

The [template.yaml](https://github.com/awslabs/ssosync/blame/3266d73389082a14db3b06723dc6201787935e5f/template.yaml#L158)  seems to match 500-600 characters. My last deploy of this a month ago seemed to work fine and I checked and that token was 583 characters long. 

Application is undeployable for me due to this. Creating PR to fix.

**Comment by xelfer** [comment]
Thanks for merging @ChrisPates - how long til that hits SAR?

**Comment by ChrisPates** [comment]
Assuming, a clean run through the pipelines, early this afternoon. 

You see a new release on the code repo and about an hour later, you should see a build of the same version in the SAR repo.

**Comment by xelfer** [comment]
wonderful, thank you!

**Comment by ChrisPates** [comment]
SAR release is now available.

**Comment by xelfer** [comment]
Thanks, confirmed deployed and working. Appreciate your help @ChrisPates
