### ISSUE TITLE
Limit groups by schema

### ISSUE THREAD

**Issue by kellertobias** [awslabs/ssosync#28]
**Is your feature request related to a problem? Please describe.**
We are using groups in gsuite not only as a real set of user groups, but also as internal mailing lists for projects or as alerting hubs for several topics. Thus we have a lot of groups. From our 100 Groups (and rising) only around 5-10 are related to actual groups in AWS.

**Describe the solution you'd like**
Add a filter to allow only groups whose emails match the filter. (e.g. `aws.*@mydomain.com` or `*@department.mydomain.com`)

**Describe alternatives you've considered**
None

**Comment by smitty-exos** [comment]
Yeah, would be nice to add just the groups you want as opposed to having to ignore a bunch of groups.
Syncing from Gsuite to AWS, we obviously only want the tech teams, not everyone in the company.
The current method of ignore group doesn't lend itself very well for this.

**Comment by talentedmrjones** [comment]
I added issue #34 as an alternative way to limit groups. In fact the groups in Google do not align with the groups in AWS SSO, so these features could co-exist: --include-groups to pull from Google, a filter on email or user attribute could determine what AWS SSO group the user gets added to

**Comment by ChrisPates** [comment]
So the above sort of query is not possible for Groups as defined by the [documentation](https://developers.google.com/admin-sdk/directory/v1/guides/search-groups). As of v2.2.0, we now support multiple search patterns for groups and now individual users can also be sync using multiple patterns.
