### ISSUE TITLE
SSOSYNC_IGNORE_GROUPS not working in lambda

### ISSUE THREAD

**Issue by wonderphil** [awslabs/ssosync#30]
**Describe the bug**
Added lambda environment var `SSOSYNC_IGNORE_GROUPS` and pointed it at a secret in secret manager but its not ignoring said groups

**To Reproduce**
Steps to reproduce the behaviour:
1. Add secret to secret manager with `group1@email.com,group2@email.com`
2. add env var to lambda called `SSOSYNC_IGNORE_GROUPS` and point it at the ARN of the above
3. run the function
4. check logs in cloud watch and see that groups are being synced

**Expected behavior**
run the function and check logs and see that groups are not being synced

**Additional context**
Won't be an issue when [PR16](https://github.com/awslabs/ssosync/pull/16) is merged as we have over 300 groups and only need to sync 3.

**Comment by joshuachong** [comment]
Hi, can you use the latest release with #16 merged?

**Comment by ChrisPates** [comment]
PR16 was merged quite sometime ago, since then various other improvements have been made. If this issue is still seen please re-open.
