### ISSUE TITLE
 googleapi: Error 400: Invalid Input, invalid

### ISSUE THREAD

**Issue by awasilyev** [awslabs/ssosync#32]
**Describe the bug**
ssosync fails with error 400

```
INFO[0000] Creating the Google and AWS Clients needed
DEBU[0000] get deleted users
WARN[0000] Error Getting Deleted Users
FATA[0000] googleapi: Error 400: Invalid Input, invalid
```

**To Reproduce**
I just did all the steps, described in the readme.
Enabled Admin api, created service account, added it to the domain wide delegation with 3 scopes, created key,
started ssosync.

**Expected behavior**

**Additional context**

**Comment by Danl2620** [comment]
Did you specify an admin email address with `--google-admin` when running?

**Comment by tmargono** [comment]
Look here for list of possible errors: https://developers.google.com/identity/protocols/oauth2/service-account?authuser=1#error-codes

Try to delete and recreate the service account.

**Comment by infosanity** [comment]
I'm experiencing the same issue as @awasilyev.

If I manually set the sync method to `users_groups` my users are retrieved as expected, before failing to collect the groups. Therefore I don't 'think' it's a permissions error.

`go run main.go \
	--access-token "<redacted>" \
	--endpoint "<redacted>" \
	--google-admin "admin@domain.tld" \
	--google-credentials credentials.json \
	--sync_method users_groups
	--debug`

Results in:
`INFO[0000] Syncing AWS users and groups from Google Workspace SAML Application
INFO[0000] syncing                                       sync_method=users_groups
INFO[0000] deleting google user                          email=user@domain.tld
FATA[0019] googleapi: Error 400: Invalid Input: query, invalid
exit status 1`

All settings are extracted from the SecretsManager variables created by the Serverless Application Repository version, which I initially deployed; but user/group count meant runtime exceeded the 15min timeout as per issue #17. This deployment is (supposedly) just migrating to longer lived infrastructure to avoid the timeout.

**Comment by joshuachong** [comment]
@awasilyev - to confirm, your issue was running on 1.0.0-rc.8? 

@infosanity - if you are using `users_group`, you can include the `--include-groups` option to limit the groups that you intend to sync. 
On a compute that is not bounded by 15 minutes, this shouldn't be an issue to move to ie, a Fargate implementation but could be limited by the SCIM API rate. 
What's your membership size if you don't mind sharing?

**Comment by ScOut3R** [comment]
I am experiencing the same issue as @awasilyev since I have upgraded to 1.0.0-rc.9. Did not have this problem with rc.8.

**Comment by infosanity** [comment]
> What's your membership size if you don't mind sharing?
roughly 500 users and 100 groups. 
Do need to review if scoping via `--include-groups` can get the process (significantly) under the 15min limitation. But equally worried about the additional overhead to update the sync pipeline in addition to the directories themselves, and the scalability restrictions should user/group requirements increase in future.

**Comment by KyleKotowick** [comment]
@joshuachong Same issue here. It syncs the users fine, then when it tries to sync the groups, I get these logs:
```
{"level":"debug","msg":"get google groups","query":"","time":"2021-12-22T23:41:15Z"}
googleapi: Error 400: Invalid Input: query, invalid: Error null
```

**Comment by ChrisPates** [comment]
If you still see this issue with version v2.x please re-open and provide details of your environment variables or cli parameters.

**Comment by ar1em** [comment]
Hi, I still have this issue with version 2.0.2. I ran it locally.

```./ssosync \
-t b75d76eb-****-****-****-eb460a4c1392:50211463-****-****-****-9bb130a44552:1SNqWocK***NDQZ4OVqkHkxJ7+IP+ufKQLw== \
-e https://scim.eu-central-1.amazonaws.com/kE3cb48c276-****-****-****-7f42c17400da/scim/v2/ \
-g 'name:*' \
-m 'name:*' \
-i d-996705cef3 \
-r eu-central-1 \
-s groups \
-d
```

output is:
```
INFO[0000] Syncing AWS users and groups from Google Workspace SAML Application
INFO[0000] syncing                                       sync_method=groups
INFO[0000] get google groups                             query="name:*"
FATA[0000] googleapi: Error 400: Invalid Input, invalid
```

**Comment by ChrisPates** [comment]
The error is coming fron the Google admin api. It does not accept ´name:*' you need to provide at least a character or two before the wildcard.

´name:AWS*' would work.

**Comment by ar1em** [comment]
@ChrisPates thanks for so quick and handy tip. 

I had one more mistake. I used Service Account email for `--google-admin` parameter. Now I am using my Google Workspace admin account, and it is working.

**Comment by emmanuelnk** [comment]
@ar1em thanks for that. That is a super important detail that isn't very clear in the docs.
