### ISSUE TITLE
Need to specify users and groups to include rather than ignore

### ISSUE THREAD

**Issue by talentedmrjones** [awslabs/ssosync#34]
I need to specify users/groups to **include** rather than ignore.

**Is your feature request related to a problem? Please describe.**
The problem I have is that the tool currently assumes that every user or group in Google should also exist in AWS SSO. This doesn't work for my organization. Only a very small list of users that exist in a single Google group should be synced to AWS SSO and I'd rather control which SSO group is used according to user attributes on the Google side. This allows for much easier management on the Google side. Furthermore as it is now the list to ignore would equal N-1; if another Google admin were to add a new group I would have to update the ignore list to avoid adding unauthorized users to AWS SSO. It would be far too easy for a group to be added without my knowledge and therefore unauthorized users would be granted access by mistake.

**Describe the solution you'd like**
I'd like to see the tool offer at least `--include-groups` and perhaps `--include-users` which would allow me to specify a shorter list of the _only_ group(s) to sync. The `--include-groups` and `--ignore-groups` flags would of course be mutually exclusive; an error would be raised if both were used together.

**Describe alternatives you've considered**
Write my own tool or continue managing users manually.

**Additional context**
Our organization includes many people in many departments besides engineering. It makes absolutely no sense to sync every person in every group when only a small subset of users actually need access to AWS. As it is, the tool forces me to ignore a very long and growing list of groups that have no relation to AWS at all. Only 1 (maybe 2) group(s) need to be synced and this would be more easily and plainly achieved via `--include-groups`

**Comment by plaguna** [comment]
This will help us immensely too. Current approach is not scalable.

**Comment by joshuachong** [comment]
Hi,
The latest release has merged #16 and #36. Hope this helps with your problem.

**Comment by awasilyev** [comment]
great feature!
it will be very nice to support not just a plain list but regex for specifying list of groups/users

**Comment by joshuachong** [comment]
@awasilyev - will you be considering a regex feature? I may want to consider this but it will take sometime on my end.
