### ISSUE TITLE
Serverless Application Repository not updated to 1.0.0-rc9

### ISSUE THREAD

**Issue by clee-newclassrooms** [awslabs/ssosync#39]
I'm trying to determine whether the #16 and #36 changes included in release 1.0.0-rc9 will improve performance sufficiently to support our group hierarchy.  However, that release is not yet available in the SAM repository.

**Comment by oleksandr-gubchenko** [comment]
@joshuachong

**Comment by oleksandr-gubchenko** [comment]
Any update on this?

**Comment by joshuachong** [comment]
Hi @oleksandr-gubchenko sorry for getting back on this late.
There's a few fixes ongoing for `1.0.0-rc.10`
Once that's done, I'll follow up on this and update the SAR template to rc10. 

That will include new environment variables for the lambda for `ignore-groups`, `ignore-users`, `include-groups`.

**Comment by clee-newclassrooms** [comment]
The last commit was over a month ago.

Through local testing it became clear that rc9 would not work with my filters anyway, but if this project is stalled I may have to roll our own sync tool.

Can we get an update about what's going on?

**Comment by lgosh** [comment]
@oleksandr-gubchenko @joshuachong Is there any update on this? Can we please at least know if this project is stalled?

@clee-newclassrooms Have you heard anything probably from somewhere other than Github?

**Comment by clee-newclassrooms** [comment]
> @clee-newclassrooms Have you heard anything probably from somewhere other than Github?

I have not.

At this point I expect that I will have to fork this project or start something new from scratch OR right about the time I have something working, Google will magically provide generic SCIM v2 support and this whole struggle will have been an enormous waste of time.  Unfortunately, I'm buried under project work right now and I have no idea when I'll have some bandwidth to work on this.

**Comment by lgosh** [comment]
I agree with Google providing generic SCIM v2 support, that would be ideal, what's taking so long for them anyway...

**Comment by cshivash-yara** [comment]
@joshuachong  Any idea when we can expect the release for this ?

**Comment by soumyadipDe** [comment]
I tried with the template.yml file directly to CloudFormaton. That also failing saying,
` Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [SSOSyncFunction] is invalid. Only one of 'InlineCode' or 'CodeUri' can be set.. Rollback requested by user.`

**Comment by soumyadipDe** [comment]
Never mind, could make it work with steps given in https://github.com/awslabs/ssosync#sam

**Comment by herbertgoto** [comment]
@joshuachong Any update on this?

**Comment by ChrisPates** [comment]
Hoping to have SSOSync back in the SAR tomorrow (assuming all testing goes to plan).

**Comment by lgosh** [comment]
Hi @ChrisPates, I still see the rc8 version in the SAR. Is this expected?

**Comment by ChrisPates** [comment]
You should be seeing [1.0.0-rc.9](https://us-east-2.console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-2:004480582608:applications/SSOSync). There are several unofficial publications under the name ssosync. The verified publisher is [AWSLabs - SSOSync](https://github.com/awslabs/ssosync).
