### ISSUE TITLE
Nested google groups are not synchronised correctly in AWS 

### ISSUE THREAD

**Issue by alexku7** [awslabs/ssosync#51]
We have nested groups in google . For example group A contains group B . The group B has a user Y.

In this scenario, In thew AWS SSO we expect to see  that the group A will have the Group B inside or the user Y directly.

Seems AWS SSO doesn"t support nested groups and the ssosync script doesn"t expand nested group recursively

**Comment by icj217** [comment]
This seems related to/a duplicate of https://github.com/awslabs/ssosync/issues/27

**Comment by ChrisPates** [comment]
duplicate of [https://github.com/awslabs/ssosync/issues/66](https://github.com/awslabs/ssosync/issues/66)
