### ISSUE TITLE
SSOSYNC_GROUP_MATCH not filtering groups in Lambda

### ISSUE THREAD

**Issue by casey-boyer-bolt-data** [awslabs/ssosync#52]
**Describe the bug**
Trying to configure `ssosync` to filter using either `name` or `email` prefix. All groups (and thus effectively all Users) are synced to AWS rather than just those matching the filter.

> As a side-issue, all groups created in AWS SSO are named based on the `email` from the Google Workspace Group, where I'd expect the `name` to match `name`.

**To Reproduce**
1. Installed SAM Application using https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:eu-west-1:084703771460:applications/ssosync
> Using version 1.0.0-rc.8 based on inspecting the CloudFormation Template, Code URI: `############/arn:aws:serverlessrepo:eu-west-1:084703771460:applications-ssosync-versions-1.0.0-rc.8/110db7d7-a2bc-4f0a-9072-8e7fd347c160`

2. Ran with args '...'

Key | Value
---- | ------
`SSOSYNC_GOOGLE_ADMIN` | `arn:aws:secretsmanager:us-east-2:############:secret:SSOSyncGoogleAdminEmail-...`
`SSOSYNC_GOOGLE_CREDENTIALS` | `arn:aws:secretsmanager:us-east-2:############:secret:SSOSyncGoogleCredentials-...`
`SSOSYNC_LOG_FORMAT` | `json`
`SSOSYNC_LOG_LEVEL` | `info`
`SSOSYNC_SCIM_ACCESS_TOKEN` | `arn:aws:secretsmanager:us-east-2:############:secret:SSOSyncSCIMAccessToken-...`
`SSOSYNC_SCIM_ENDPOINT` | `arn:aws:secretsmanager:us-east-2:############:secret:SSOSyncSCIMEndpointUrl-...`
`SSOSYNC_SYNC_METHOD` | `groups`
`SSOSYNC_GROUP_MATCH` | `name:'My Company Access Group - AWS*'` (also tried `email:aws-*`, `name:aws-*`, `name:aws`, and `email:aws`

3. Inspect logs and see *all* groups being synced.

**Expected behavior**
Expect only those Groups matching the filter defined by `SSOSYNC_GROUP_MATCH` to sync from Google Workspace. I would think if it was just a bad filter, I would get 0 groups/users synced, but the fact that everything syncs makes it seem like the variable isn't being read.

**Additional context**
Found the instructions for set-up of this from: https://controltower.aws-management.tools/aa/sso/google/.

**Comment by treylon** [comment]
I ran into the same problem. When scanning the bundled code in version 1.0.0-rc.8 I could not find the  group match feature, it seems to have been added afterwards since it turns up in the current state of the repository. Probably this would be fixed by just re-publishing the current release to the AWS Serverless Application Repository.

@joshuachong Is there a reason the new version has not been published to the AWS Serverless Application Repository?

**Comment by cfir-atbay** [comment]
+1

**Comment by applike-ss** [comment]
try using this one instead: `arn:aws:serverlessrepo:us-east-2:004480582608:applications/SSOSync`

**Comment by ChrisPates** [comment]
This issue should be resolved in version 1.0.0-rc10 onwards.
