### ISSUE TITLE
Unclear required --include-groups with --sync-method ‘users_groups’

### ISSUE THREAD

**Issue by b4nst** [awslabs/ssosync#53]
**Describe the bug**
Reading the documentation, when using the `--sync-method ‘users_groups’`, my understanding is that `--include-groups` should be optional and include every groups by default. However when not using the option every groups are silently ignored. 
Indeed when looking at 
https://github.com/awslabs/ssosync/blob/6220679fd3cce62ebd9774144a292008896d297c/internal/sync.go#L178-L181
we can see that if `s.includeGroup` return false, the group is ignored. And `s.includeGroup` **will** return false if the group is not in `--include-groups` (so every single groups if `--include-groups` is empty).

https://github.com/awslabs/ssosync/blob/6220679fd3cce62ebd9774144a292008896d297c/internal/sync.go#L745-L753

**To Reproduce**
1. Run sso sync with `--sync-method ‘users_groups’` and no `--include-groups`
3. See no group created

**Expected behavior**
Every groups should be included

**Comment by b4nst** [comment]
Btw the reason I'm using `users_groups` over `groups` is because I'm facing #45

**Comment by ChrisPates** [comment]
This is resolved by release v2.0.3
