### ISSUE TITLE
Error when deploy lambda error after sam application manually

### ISSUE THREAD

**Issue by cfir-atbay** [awslabs/ssosync#56]
**Describe the bug**
Trying to deploy sam application manually after deploy the lambda crash 

**To Reproduce**
Environment Vars:

SSOSYNC_GOOGLE_ADMIN | arn:aws:secretsmanager:us-east-1:*:secret:*
SSOSYNC_GOOGLE_CREDENTIALS | arn:aws:secretsmanager:us-east-1:*:*
SSOSYNC_GROUP_MATCH | email:somePrefix*
SSOSYNC_LOG_FORMAT | text
SSOSYNC_LOG_LEVEL | info
SSOSYNC_SCIM_ACCESS_TOKEN | arn:aws:secretsmanager:us-east-1:*:*
SSOSYNC_SCIM_ENDPOINT | arn:aws:secretsmanager:us-east-1:*:*
SSOSYNC_SYNC_METHOD | groups

Error:

`[{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/errors.go","line":39,"label":"lambdaPanicResponse"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/function.go","line":36,"label":"(*Function).Invoke.func1"},{"path":"runtime/panic.go","line":965,"label":"gopanic"},{"path":"runtime/panic.go","line":212,"label":"panicmem"},{"path":"runtime/signal_unix.go","line":734,"label":"sigpanic"},{"path":"cfir/git/ssosync/internal/google/client.go","line":45,"label":"NewClient"},{"path":"cfir/git/ssosync/internal/sync.go","line":687,"label":"DoSync"},{"path":"cfir/git/ssosync/cmd/root.go","line":55,"label":"glob..func1"},{"path":"github.com/spf13/cobra@v1.1.3/command.go","line":852,"label":"(*Command).execute"},{"path":"github.com/spf13/cobra@v1.1.3/command.go","line":960,"label":"(*Command).ExecuteC"},{"path":"github.com/spf13/cobra@v1.1.3/command.go","line":897,"label":"(*Command).Execute"},{"path":"reflect/value.go","line":476,"label":"Value.call"},{"path":"reflect/value.go","line":337,"label":"Value.Call"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/handler.go","line":124,"label":"NewHandler.func1"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/handler.go","line":24,"label":"lambdaHandler.Invoke"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/function.go","line":64,"label":"(*Function).Invoke"},{"path":"reflect/value.go","line":476,"label":"Value.call"},{"path":"reflect/value.go","line":337,"label":"Value.Call"},{"path":"net/rpc/server.go","line":377,"label":"(*service).call"},{"path":"runtime/asm_amd64.s","line":1371,"label":"goexit"}]
END RequestId: ab43f97f-ab0f-4292-a001-53529de7b2fc
REPORT RequestId: ab43f97f-ab0f-4292-a001-53529de7b2fc	Duration: 1110.06 ms	Billed Duration: 1111 ms	Memory Size: 128 MB	Max Memory Used: 53 MB	Init Duration: 147.93 ms	
runtime error: invalid memory address or nil pointer dereference
errorString
`
**Sam properties**
    SemanticVersion: 1.0.0-rc.9
    SourceCodeUrl: https://github.com/awslabs/ssosync/tree/1.0.0-rc.9

**Comment by Luis-3M** [comment]
@cfir-atbay 
Facing this exact same issue atm - has anyone been able to solve this?
According to this stack trace it seems to fail right here `config.Subject = adminEmail` but I'm not yet able to understand why.
Works perfectly on my local machine.

**Comment by Luis-3M** [comment]
@cfir-atbay 
Finally managed to fix it.
1) When adding secrets to SM make sure that them as plain text
2) Google credentials require 1 row per key to be added to SM, so just copy the content of your `credentials.json` and add it in the Plaintext section of SM. You should then see the expected output.

PS: https://github.com/awslabs/ssosync/blob/master/internal/google/client.go#L45-L49
This piece of code should be swapped, otherwise we will me mislead by the error message above and it will cover up the actual error which comes from `google.JWTConfigFromJSON`.

**Comment by Luis-3M** [comment]
@ChrisPates thank you for merging PR #62 . This issue can now be closed.
