### ISSUE TITLE
Is is no longer available in AWS Serverless Application Repository.

### ISSUE THREAD

**Issue by mateimicu** [awslabs/ssosync#60]
**Describe the bug**
Following the link [AWS Serverless Application Repository](https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:eu-west-1:084703771460:applications/ssosync) from the [readme](https://github.com/awslabs/ssosync#aws-lambda-usage) results in an error `You are not authorized to perform: serverlessrepo:GetApplication.`

I think it is no longer available in the repository. Is this something intended ?

**To Reproduce**
1. Login to an was account with admin privileges 
2. Click [AWS Serverless Application Repository](https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:eu-west-1:084703771460:applications/ssosync)
3. See error `You are not authorized to perform: serverlessrepo:GetApplication.`

**Expected behavior**
I was expanding to find the app and be able to create a stack out of it.

**Additional context**
We figure this out by trying to update an existing stack

**Comment by InbarRose** [comment]
i confirm this happens for me as well.

**Comment by denniswebb** [comment]
Same here

**Comment by mani1soni** [comment]
Is there any alternative for doing this?

**Comment by christiangda** [comment]
well since a couple of months ago I created a new OSS project to resolve this problem.  I still working on that in my free time and it is almost ready,  in fact, I'm testing it with good results, so I hope  I can release this close.

I'm working in the development branch, and de docs still pending
https://github.com/slashdevops/idp-scim-sync/tree/develop

This is a WIP with a new approach to reduce the was so scim API calls storing the state in an S3 bucket.

**Comment by mateimicu** [comment]
One workaround would be to use [SAM](https://github.com/awslabs/ssosync#sam) to deploy the same lambda.

**Comment by mani1soni** [comment]
Thanks, @christiangda and @mateimicu.

**Comment by mani1soni** [comment]
@mateimicu We checked  with SAM, but we are facing the following error while executing the SSOSync lambda function.
`googleapi: Error 404: Domain not found., notFound: Error null`
Is there any fix available or any way to validate our parameters given, Google Suite & AWS SSO setup?
![image](https://user-images.githubusercontent.com/30206849/140494028-d2cc08b4-4710-4fd3-b9ba-e73e54b503a7.png)

**Comment by mateimicu** [comment]
@mani1soni I am not sure of any alternative to check the SSO setup. Sounds like a token problem but I am not familiar with the project.

**Comment by mani1soni** [comment]
ohh, okay, thanks @mateimicu, i'll check.

**Comment by xposix** [comment]
Just to add pressure on this. I'm having the same issue. I can't deploy this lambda function using Terraform anymore. It would be nice to have the serverless repo back on, even if it's on another account.

**Comment by ShyWiz** [comment]
@katallaxie @christiangda Any updates on this?

**Comment by christiangda** [comment]
Hi guys, I finished the first version of the new alternative project to this one.

https://github.com/slashdevops/idp-scim-sync is a fresh implementation, it is not a `ssosync` fork, and the main idea is to keep a "state file" after the sync to avoid unnecessary requests to AWS SSO SCIM API.

this project is composed of different artefacts repository but the most convenient one is the `AWS Serverless Application` https://serverlessrepo.aws.amazon.com/applications/us-east-1/889836709304/idp-scim-sync

**Comment by Zemnmez** [comment]
Don't really understand why this really key feature is essentially broken

**Comment by JubbaSmail** [comment]
still facing the same issue here

**Comment by ChrisPates** [comment]
Aiming to have the app back in the SAR tomorrow assuming testing goes to plan. Apologies for its disappearance.

**Comment by ChrisPates** [comment]
Available in the Serverless Application Repository : [SSOSync](https://eu-west-1.console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-2:004480582608:applications/SSOSync)

**Comment by ThisIsQasim** [comment]
it looks like the version in SAR is rc8. Can we expect this to updated to rc10?

**Comment by ChrisPates** [comment]
The old AWS Account that hosted this application in SAR, is no longer available. There is a ssosync app published by someone else at rc8 but the official app is available under in the Serverless Application Repository : [SSOSync](https://eu-west-1.console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-2:004480582608:applications/SSOSync) it is currently rc9. 

The rc9 build was created and published manually, I'll push rc10 just as soon as I have validated the CICD pipeline for publication.

**Comment by ThisIsQasim** [comment]
My bad. It is indeed rc9. Would appreciate if rc10 could be published.

**Comment by ChrisPates** [comment]
rc10 has been released.

**Comment by ThisIsQasim** [comment]
Thank you fir the swift response. Much appreciated!

**Comment by ThisIsQasim** [comment]
@ChrisPates the lambda function in the new template is now failing with the following

```
fork/exec /var/task/dist/ssosync_linux_amd64/ssosync: no such file or directory:
```

**Comment by ChrisPates** [comment]
That was a breaking change in goreleaser and was fixed in [Back in SAR](https://github.com/awslabs/ssosync/commit/dde1058a2a37072f03ad0f4ebc2f45eead4b6341), your clone is possibly stale.

**Comment by ThisIsQasim** [comment]
I didn't clone. Just using the new version from SAR

**Comment by ThisIsQasim** [comment]
Looks like I was using some outdated version. I followed the link from this repo and everything is working normal again.
