### ISSUE TITLE
Googleapi: Error 404: Domain not found., notFound

### ISSUE THREAD

**Issue by liammekler** [awslabs/ssosync#64]
I have deployed the solution via SAM, the deployment went well  but running the lambda function results in the following error:

`FATA[0000] googleapi: Error 404: Domain not found., notFound`

Please advise,
Thanks

**Comment by Korede-TA** [comment]
+1

running this locally as `ssosync -d -c credentials.json -g 'email=group-alias@company.com'`

**Comment by chandra217** [comment]
We are facing the same error while executing the SSOSync lambda function.
`googleapi: Error 404: Domain not found., notFound: Error null`
Is there any fix available or any way to validate our parameters given, Google Suite & AWS SSO setup?


<img width="1075" alt="Screenshot 2021-11-05 at 3 33 32 PM" src="https://user-images.githubusercontent.com/69146352/140493580-998edc52-297b-41d9-a877-768d50588d58.png">

**Comment by scristian** [comment]
I think is because of this section that I did not finalised, as is not clear how:
```
Back in the Console go to the Dashboard for the API & Services and select "Enable API and Services". In the Search box 
type Admin and select the Admin SDK option. Click the Enable button.

You will have to specify the email address of an admin via --google-admin to assume this users role in the Directory.
```

**Comment by chandra217** [comment]
@scristian Thanks for the response.  
I've double checked those you mentioned, 
- Enabled API and Services
- Added google admin email address
Still we are getting the same error `googleapi: Error 404: Domain not found., notFound: Error null`
Could you please help us to fix this or is there any other solution for auto user provisioning from G-Suite to AWS SSO ?

**Comment by scristian** [comment]
> @scristian Thanks for the response. I've double checked those you mentioned,
> 
> * Enabled API and Services
> * Added google admin email address
>   Still we are getting the same error `googleapi: Error 404: Domain not found., notFound: Error null`
>   Could you please help us to fix this or is there any other solution for auto user provisioning from G-Suite to AWS SSO ?

In my case I managed to fix it by using --google-admin

**Comment by chandra217** [comment]
`404 Error` has been resolved and all working fine. Thank you @scristian
