### ISSUE TITLE
Lack of support for nest groups

### ISSUE THREAD

**Issue by robotica-labs** [awslabs/ssosync#66]
**Describe the bug**
When running SSO Sync receive error message:  
Exception has occurred: panic
"runtime error: index out of range [0] with length 0"
Stack:
	 3  0x0000000000eca5d3 in github.com/awslabs/ssosync/internal.(*syncGSuite).getGoogleGroupsAndUsers
	     at C:/Users/matth/Desktop/Stuff/AWS SSO/SSOSYNC/ssosync/internal/sync.go:511
	 4  0x0000000000ec6ae7 in github.com/awslabs/ssosync/internal.(*syncGSuite).SyncGroupsUsers
	     at C:/Users/matth/Desktop/Stuff/AWS SSO/SSOSYNC/ssosync/internal/sync.go:291
	 5  0x0000000000ecceec in github.com/awslabs/ssosync/internal.DoSync
	     at C:/Users/matth/Desktop/Stuff/AWS SSO/SSOSYNC/ssosync/internal/sync.go:706
	 6  0x0000000000fee6ab in github.com/awslabs/ssosync/cmd.glob..func1
	     at C:/Users/matth/Desktop/Stuff/AWS SSO/SSOSYNC/ssosync/cmd/root.go:55
	 7  0x0000000000fb2f70 in github.com/spf13/cobra.(*Command).execute
	     at C:/Users/matth/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852
	 8  0x0000000000fb3ce6 in github.com/spf13/cobra.(*Command).ExecuteC
	     at C:/Users/matth/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
	 9  0x0000000000fb33ef in github.com/spf13/cobra.(*Command).Execute
	     at C:/Users/matth/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
	10  0x0000000000fecec5 in github.com/awslabs/ssosync/cmd.Execute
	     at C:/Users/matth/Desktop/Stuff/AWS SSO/SSOSYNC/ssosync/cmd/root.go:72
	11  0x0000000000fee877 in main.main
	     at C:/Users/matth/Desktop/Stuff/AWS SSO/SSOSYNC/ssosync/main.go:29

Error hits sync.go line 511:  membersUsers = append(membersUsers, u[0])

u evaluates to "[]*google.golang.org/api/admin/directory/v1.User len: 0, cap: 0, []"

I am trying to sync a small subset of groups and about 40-80 users from Gsuite to AWS SSO. I cannot sync all user accounts and groups, it has to be a subset.

**To Reproduce**
1. Debug mode with VSCode
2. Ran with args using launch.json (sanitized here) to pass args.
"args": [
       ...
        "--google-admin",
        "meisadmin@mygsuitedomain.com",
        "--sync-method",
        "groups",
        "--ignore-users",
        "email:*",
        "--include-groups",
        "name:mygroupaddress@mygsuitedomain.com"
      ]
3. See error

**Expected behavior**
Expect it to continue and finish process.

**Additional context**
https://alegiovanardi.medium.com/go-slices-explained-part-1-1f1143b568fc seems to indicate that the array (or slice) is too small. I'm not sure why because it appears to be dynamically assigned.  I've spent several hours trying to fix it, but I have no experience with GOLang and can't get over that hurdle.
This gsuite domain has thousands of user accounts.

Thanks for your attention

**Comment by christiangda** [comment]
Hi guys, I finished the first version of the new alternative project to this one.

https://github.com/slashdevops/idp-scim-sync is a fresh implementation, it is not a `ssosync` fork, and the main idea is to keep a "state file" after the sync to avoid unnecessary requests to AWS SSO SCIM API.

this project is composed of different artefacts repository but the most convenient one is the `AWS Serverless Application` https://serverlessrepo.aws.amazon.com/applications/us-east-1/889836709304/idp-scim-sync

**Comment by omerls-pw** [comment]
when will this fix be merged to `main`?

**Comment by ChrisPates** [comment]
v2.0.2 no longer panics but simply ignores group members that are themselves groups. I'll be looking to implement a 'group flattening' approach in a future feature branch.

**Comment by naharoo** [comment]
Hi. Any ETA on implementing group flattening?

**Comment by omerls-pw** [comment]
@naharoo 
they published another way to sync `users` only.
https://docs.aws.amazon.com/singlesignon/latest/userguide/gs-gwp.html

**Comment by ChrisPates** [comment]
I’m hoping to get to this in v2.2, there is an official integration although the feedback I’ve received is that the lack of support for groups means folk want to continue with ssosync for now.


Chris


On 14 Jan 2024, at 12:28, Omer Livne ***@***.***> wrote:

﻿


@naharoo
they published another way to sync users only.
https://docs.aws.amazon.com/singlesignon/latest/userguide/gs-gwp.html <https://docs.aws.amazon.com/singlesignon/latest/userguide/gs-gwp.html>
