### ISSUE TITLE
Lambda Environment Variables are not actually used

### ISSUE THREAD

**Issue by mettke** [awslabs/ssosync#67]
**Describe the bug**
The template.yaml files contains the following environment variables:
```          
SSOSYNC_GOOGLE_CREDENTIALS: !Ref AWSGoogleCredentialsSecret
SSOSYNC_GOOGLE_ADMIN: !Ref AWSGoogleAdminEamil
SSOSYNC_SCIM_ENDPOINT: !Ref AWSSCIMEndpointSecret
SSOSYNC_SCIM_ACCESS_TOKEN: !Ref AWSSCIMAccessTokenSecret
```

These variables, however, are not actually used in the source code. Instead [secrets.go](https://github.com/awslabs/ssosync/blob/master/internal/config/secrets.go) contains hard coded values.

**Expected behavior**
Environment Variables should be used to allow configuration of the ssosync app.

**Comment by ChrisPates** [comment]
Those four variables are stored in [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/), to ensure security of the data. They are configurable without redeployment as they can be updated directly in AWS Secrets Manager, and SSOSync will use them on its next execution.

**Comment by Benbentwo** [comment]
Unfortunately, this is not resolved, the fact of the matter is that based on the latest version at this time (2.0.2) you are unable to deploy the release artifacts without the use of AWS Secrets Manager. This presents a problem in that you must use Secrets Manager as opposed to any other Secret Store.

This is a simple CLI that should be deployable anywhere via any methodology such as AWS Lambda, Kubernetes, or a simple bash script.
