### ISSUE TITLE
Unsupported Protocol Scheme

### ISSUE THREAD

**Issue by akashrpatel** [awslabs/ssosync#68]
Running ./ssosync -c ~/credentials.json --google-admin "name@company.com" --group-match 'name:aws-admin*' --debug

Results:
NFO[0000] Syncing AWS users and groups from Google Workspace SAML Application
INFO[0000] syncing                                       sync_method=groups
DEBU[0000] get google groups                             query="name:aws-admin*"
DEBU[0000] get google users and groups and its users
DEBU[0000] get group members from google                 group=aws-administrators
DEBU[0001] get users                                     group=aws-administrators
DEBU[0001] get user                                      group=aws-administrators id=name@company.com
DEBU[0001] get user                                      group=aws-administrators id=name2@company.com
DEBU[0002] get aws groups
INFO[0002] [DEBUG] GET /Groups
INFO[0002] [ERR] GET /Groups request failed: Get "/Groups": unsupported protocol scheme ""
ERRO[0002] error getting aws groups
FATA[0002] Get "/Groups": GET /Groups giving up after 1 attempt(s): Get "/Groups": unsupported protocol scheme ""

Any info would be appreciated.

Thank you,
Akash

**Comment by scristian** [comment]
Hey @akashrpatel did you find a solution for this? 
Thank you!

**Comment by scristian** [comment]
I fixed the issues by exporting SSOSYNC_SCIM_ENDPOINT and SSOSYNC_SCIM_ACCESS_TOKEN

**Comment by ChrisPates** [comment]
So this fail was not throwing an error when those environment variables were not available. This was fixed in v2.1.4 with additional endpoint tests and in v2.2.0 with enhance error messaging for enVars.
