### ISSUE TITLE
Groups with colons fail to be created

### ISSUE THREAD

**Issue by grugnog** [awslabs/ssosync#7]
**Describe the bug**
Groups with colons fail to be created

**To Reproduce**
1. Create a group in GSuite containing a colon in the display name - e.g. `Hello: there`
2. Run ssosync as you normally would, with the `--debug` flag
3. You get error `FATA[0019] status of http response was 400`

**Expected behavior**

The group is created!

**Additional context**

There are various approaches that could resolve this - for example:

- AWS SSO is updated to accept colons
- The colons are filtered out by awssso
- The group system name (i.e. the e-mail address name) is used instead of the display name
- Improved docs and error messages to call this out, so that people can update their display names in GSuite

**Comment by katallaxie** [comment]
@grugnog I would side with the email address as the group name. I will have to test this.
