### ISSUE TITLE
Bug: "index out of range [0] with length 0"

### ISSUE THREAD

**Issue by bkmeneguello** [awslabs/ssosync#76]
When [this call](https://github.com/awslabs/ssosync/blob/v1.0.0-rc.9/internal/sync.go#L485) of `GetUsers` returns an empty list in `getGoogleGroupsAndUsers`, the `index out of range [0] with length 0` error occurs [here](https://github.com/awslabs/ssosync/blob/v1.0.0-rc.9/internal/sync.go#L490).

**Comment by Smana** [comment]
I've the exact same error, is there a workaround?

**Comment by bkmeneguello** [comment]
Yes, my PR #78

**Comment by christiangda** [comment]
check it: https://github.com/slashdevops/idp-scim-sync

**Comment by Smana** [comment]
thanks @bkmeneguello , I confirmed that worked :)

**Comment by christiangda** [comment]
@Smana this is available like a lambda, cli and container.

**Comment by Smana** [comment]
I'll test it too, thanks for letting me know @christiangda

**Comment by enricopesce** [comment]
Is it the project died? Why this PR is not merged?
