### ISSUE TITLE
The active/disabled status isn't synced from Google to AWS SSO

### ISSUE THREAD

**Issue by jverhoeks** [awslabs/ssosync#8]
**Is your feature request related to a problem? Please describe.**
When a user is relieved of duty this is done by disabling the User in GSuite. It's important that the access in Aws is also removed. Deleting a user is done after a period.

**Describe the solution you'd like**
I created a PR that sync the the flag to the user.  In SSO the flag is called Active, in GSuite Disable. 
The added logic is 
At Create: Pass the Active Flag for the user object
At Update: The Active state is retrieved from AWS and verified with the Gsuite Disabled Flag. Is this is changed the user is updated. Herefor a new function UpdateUser is created.

**Additional context**

**Comment by katallaxie** [comment]
@jverhoeks good catch, let's work on the PR.

**Comment by jverhoeks** [comment]
The code is merged.
