### ISSUE TITLE
Doesn't support more than 50 users

### ISSUE THREAD

**Issue by sjf3** [awslabs/ssosync#81]
**Describe the bug**
https://github.com/awslabs/ssosync/blob/cb8a8aaa83cb555ec4ba2f7bcaaf628c269b6b67/internal/aws/client.go#L541
GetUsers call doesn't support pagination and according to your docs here https://docs.aws.amazon.com/singlesignon/latest/developerguide/listusers.html the max results returned is 50. This means only 50 existing users will ever be returned and diffed with the users in gsuite resulting in users that already exist trying to be re-created and the entire sync process failing on 409 errors on user creation of a user that already exits

**To Reproduce**
Have more than 50 users being synced and watch the 409s pour in

**Expected behavior**
Support more than 50 users

**Additional context**
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                   message                                                                                    |
|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1646431741449 | START RequestId: ccb39549-b4d2-4a8a-b5e8-89071d8eaac4 Version: $LATEST                                                                                                       |
| 1646431742502 | {"level":"info","msg":"Syncing AWS users and groups from Google Workspace SAML Application","time":"2022-03-04T22:09:02Z"}                                                   |
| 1646431742502 | {"level":"info","msg":"syncing","sync_method":"groups","time":"2022-03-04T22:09:02Z"}                                                                                        |
| 1646431742502 | {"level":"info","msg":"get google groups","query":"name:aws-* email:aws-*","time":"2022-03-04T22:09:02Z"}                                                                    |
| 1646431778089 | {"level":"info","msg":"get existing aws groups","time":"2022-03-04T22:09:38Z"}                                                                                               |
| 1646431778153 | {"level":"info","msg":"get existing aws users","time":"2022-03-04T22:09:38Z"}                                                                                                |
| 1646431823124 | {"level":"info","msg":"syncing changes","time":"2022-03-04T22:10:23Z"}                                                                                                       |
| 1646431823160 | {"level":"warning","msg":"deleting user","time":"2022-03-04T22:10:23Z","user":"a@***********"}                                                                             |
| 1646431823406 | {"level":"info","msg":"creating user","time":"2022-03-04T22:10:23Z","user":"t@*************"}                                                                                  |
| 1646431823470 | {"level":"error","msg":"error creating user","time":"2022-03-04T22:10:23Z","user":"t@************"}                                                                           |
| 1646431823471 | status of http response was 409: errorString null                                                                                                                            |
| 1646431823472 | END RequestId: ccb39549-b4d2-4a8a-b5e8-89071d8eaac4                                                                                                                          |
| 1646431823472 | REPORT RequestId: ccb39549-b4d2-4a8a-b5e8-89071d8eaac4 Duration: 82020.83 ms Billed Duration: 82021 ms Memory Size: 128 MB Max Memory Used: 51 MB Init Duration: 191.18 ms   |

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

email addresses redacted

**Comment by jeevan-cyriac** [comment]
any suggestions on fixing this problem? Is this a limitation of AWS SSO SCIM APIs? Any workarounds?

**Comment by liebman** [comment]
I've created a fork that uses a backing store to store a copy of user and group lists to work around this oversight/bug.  Its located [here](https://github.com/liebman/ssosync/tree/patched-with-pr-55-58-47-45-and-datastore) and also has several of the pending PR's applied as listed at the top of the readme.  Be sure to use branch `patched-with-pr-55-58-47-45-and-datastore`.

**Comment by jeevan-cyriac** [comment]
@liebman thank you. do you have your forked version published to AWS SAR?

**Comment by ChrisPates** [comment]
Apologies, this project has got the attention its needed for a little while now, as it stands we've got 14 outstanding PRs and we appreciate folks efforts and contributions but it will take us a little time to work through them.

**Comment by liebman** [comment]
> @liebman thank you. do you have your forked version published to AWS SAR?

Sorry no - we are running it in an on-prem kubernetes deployment.

**Comment by jeevan-cyriac** [comment]
@liebman thankyou. would be kind enough to update the README on your fork? https://github.com/liebman/ssosync/tree/patched-with-pr-55-58-47-45-and-datastore#aws-lambda-usage

I was getting confused reading the README

**Comment by drdaeman** [comment]
Hey, thanks for your fork!

I've had to do this https://github.com/janetechinc/ssosync/commit/bcd0172360315175bfd6b4edc0f3cf6590de89f2 to help it with the initial run with groups already synced by a previous version of ssosync. Otherwise, with an empty datastore it tried to create all those groups anew, crashing with HTTP 409, learning about one preexisting group per run.

**Comment by ChrisPates** [comment]
This should have been resolved by v2.x of the function.
