### ISSUE TITLE
Permission error when creating ssosync Lambda function

### ISSUE THREAD

**Issue by coltondick** [awslabs/ssosync#85]
**Describe the bug**

Error:
`You are not authorized to perform: serverlessrepo:GetApplication`

Error is thrown when attempting to create the ssosync function in AWS via the create url [https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:eu-west-1:084703771460:applications/ssosync](https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:eu-west-1:084703771460:applications/ssosync)

**To Reproduce**
1. Go to [README](https://github.com/awslabs/ssosync#aws-lambda-usage)
2. Click on [AWS Serverless Application Repository](https://console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:eu-west-1:084703771460:applications/ssosync).
3. See error
![image](https://user-images.githubusercontent.com/5271960/170099295-bb27cb0c-0cf3-4b82-a2d8-d5294d5110e0.png)

**Expected behavior**
I would expect access to be able to create the function as per the lab. 

**Additional context**

**Comment by ChrisPates** [comment]
Available in the Serverless Application Repository : [SSOSync](https://eu-west-1.console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:us-east-2:004480582608:applications/SSOSync). Which lab were you following?

**Comment by jeevan-cyriac** [comment]
Please update README with the new SAR link -  https://github.com/awslabs/ssosync/blob/master/README.md#aws-lambda-usage

**Comment by ChrisPates** [comment]
Apologies, missed that link on the last update.
