### ISSUE TITLE
Allow specifying secret ARNs

### ISSUE THREAD

**Issue by KyleKotowick** [awslabs/ssosync#92]
**Is your feature request related to a problem? Please describe.**
My secrets (`SSOSyncGoogleAdminEmail`, `SSOSyncSCIMAccessToken`, `SSOSyncSCIMEndpointUrl`, `SSOSyncGoogleCredentials`) are stored in a separate AWS account (in the same Organization). Cross-account sharing is correctly set up.

However, since the secret names are hardcoded in this application, there's no way to configure it to load secrets from a different account.

**Describe the solution you'd like**
As command line parameters and/or environment variables, allow specifying full ARNs for the secrets that should be used.

**Comment by pecigonzalo** [comment]
I don't know if I should open a new issue or we should re-open this one, but I believe that while the CF stack takes an ARN, the code is still hardcoded, and does not respect the ARN. This means the secret names themselves must be exactly set or they fail.
