### ISSUE TITLE
SSO Sync not working for google workspaces user to SSO

### ISSUE THREAD

**Issue by Rajchandraraj** [awslabs/ssosync#96]
**Describe the bug**
when you run the function it is not populating the user on AWS site , and when you check the lambda function error that we are getting is 

"runtime error: invalid memory address or nil pointer dereference: errorString [{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/errors.go","line":39,"label":"lambdaPanicResponse"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/function.go","line":36,"label":"(*Function).Invoke.func1"},{"path":"runtime/panic.go","line":838,"label":"gopanic"},{"path":"runtime/panic.go","line":220,"label":"panicmem"},{"path":"runtime/signal_unix.go","line":818,"label":"sigpanic"},{"path":"output/src608454744/src/internal/google/client.go","line":45,"label":"NewClient"},{"path":"output/src608454744/src/internal/sync.go","line":687,"label":"DoSync"},{"path":"output/src608454744/src/cmd/root.go","line":55,"label":"glob..func1"},{"path":"github.com/spf13/cobra@v1.1.3/command.go","line":852,"label":"(*Command).execute"},{"path":"github.com/spf13/cobra@v1.1.3/command.go","line":960,"label":"(*Command).ExecuteC"},{"path":"github.com/spf13/cobra@v1.1.3/command.go","line":897,"label":"(*Command).Execute"},{"path":"reflect/value.go","line":556,"label":"Value.call"},{"path":"reflect/value.go","line":339,"label":"Value.Call"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/handler.go","line":124,"label":"NewHandler.func1"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/handler.go","line":24,"label":"lambdaHandler.Invoke"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/function.go","line":64,"label":"(*Function).Invoke"},{"path":"reflect/value.go","line":556,"label":"Value.call"},{"path":"reflect/value.go","line":339,"label":"Value.Call"},{"path":"net/rpc/server.go","line":381,"label":"(*service).call"},{"path":"runtime/asm_amd64.s","line":1571,"label":"goexit"}]"

**To Reproduce**
Steps to reproduce the behavior follow the steps mentioned in the link below.
https://github.com/awslabs/ssosync#readme

**Comment by lrh00000** [comment]
We are having the same issue throwing "invalid memory address or nil pointer dereference" error.

runtime error: invalid memory address or nil pointer dereference: errorString
[{
    "path": "github.com/aws/aws-lambda-go@v1.17.0/lambda/function.go",
    "line": 36,
    "label": "(*Function).Invoke.func1"
},{
    "path": "runtime/panic.go",
    "line": 969,
    "label": "gopanic"
},{
    "path": "runtime/panic.go",
    "line": 212,
    "label": "panicmem"
},{
    "path": "runtime/signal_unix.go",
    "line": 720,
    "label": "sigpanic"
},{
    "path": "doels/Gits/ssosync/internal/google/client.go",
    "line": 44,
    "label": "NewClient"
},{
    "path": "doels/Gits/ssosync/internal/sync.go",
    "line": 251,
    "label": "DoSync"
},{
    "path": "doels/Gits/ssosync/cmd/root.go",
    "line": 54,
    "label": "glob..func1"
},{
    "path": "github.com/spf13/cobra@v1.0.0/command.go",
    "line": 842,
    "label": "(*Command).execute"
},{
    "path": "github.com/spf13/cobra@v1.0.0/command.go",
    "line": 950,
    "label": "(*Command).ExecuteC"
},{
    "path": "github.com/spf13/cobra@v1.0.0/command.go",
    "line": 887,
    "label": "(*Command).Execute"
},{
    "path": "reflect/value.go",
    "line": 475,
    "label": "Value.call"
},{
    "path": "reflect/value.go",
    "line": 336,
    "label": "Value.Call"
},{
    "path": "github.com/aws/aws-lambda-go@v1.17.0/lambda/handler.go",
    "line": 124,
    "label": "NewHandler.func1"
},{
    "path": "github.com/aws/aws-lambda-go@v1.17.0/lambda/handler.go",
    "line": 24,
    "label": "lambdaHandler.Invoke"
},{
    "path": "github.com/aws/aws-lambda-go@v1.17.0/lambda/function.go",
    "line": 69,
    "label": "(*Function).Invoke"
},{
    "path": "reflect/value.go",
    "line": 475,
    "label": "Value.call"
},{
    "path": "reflect/value.go",
    "line": 336,
    "label": "Value.Call"
},{
    "path": "net/rpc/server.go",
    "line": 377,
    "label": "(*service).call"
},{
    "path": "runtime/asm_amd64.s",
    "line": 1374,
    "label": "goexit"
}]

**Comment by ChrisPates** [comment]
Do you still see this error with the latest release v2.0.2?
