### ISSUE TITLE
Not able to pass two different groups name using lambda function. 

### ISSUE THREAD

**Issue by megha4thcloud** [awslabs/ssosync#98]
I want to add two groups from GSUIT to AWS SSO. abc@example.com and cdf@example.com but not sure how to pass it? 

In GoogleGroupMatch I am trying to give email:abc*,email:cdf* but not getting anything in debugging log also not creating any user. Please help me How to pas two different groups?

**Comment by bmb5** [comment]
+1

**Comment by treylon** [comment]
@megha4thcloud I ran into the same issue - it seems that Google only supports `AND` as an operator when specifying multiple clauses. https://developers.google.com/admin-sdk/directory/v1/guides/search-groups

Is it planned to allow multiple clauses manually throw implementing it on ssosync side?

**Comment by ChrisPates** [comment]
Working on this feature in the linked branch.

**Comment by ChrisPates** [comment]
Duplicate of [How to format multiple groups under groupmatch](https://github.com/awslabs/ssosync/issues/69#top)](https://github.com/awslabs/ssosync/issues/69)
